title: Jiale Liang's Homepage
page-top-title: Jiale Liang
top-section-bg-text: Artificial Intelligence
home-subtitle: Jiale Liang&ensp;|&ensp;梁家乐
copyright-text: '&copy; Jiale Liang 2023-2024. All Rights Reserved.'
